### ISSUE TITLE
Elaborate on Github Permissions

### ISSUE THREAD

**Issue by asachs01** [sensu/bonsai-asset-index#117]
A user opened up https://github.com/sensu/sensu-docs/issues/1291 against the docs site, and while yes, there could be some elaboration there on the permissions needed, I'm curious about the level of permissions needed when creating an asset on Bonsai. They seem pretty extensive. Are all the permissions actually needed? If not, can we trim them down so that only what's needed is requested?

**Comment by mbiang** [comment]
Adding another screenshot of the permissions we request:

<img width="598" alt="Screenshot 2019-03-08 14 57 54" src="https://user-images.githubusercontent.com/155588/54055418-a1708200-41b2-11e9-8e7e-8f182322c307.png">

**Comment by pzupan** [comment]
The permissions need to be set on the account authorizing the query to the Github endpoint.  

https://developer.github.com/apps/managing-github-apps/editing-a-github-app-s-permissions/

**Comment by portertech** [comment]
We (Sensu Inc) need to update the permission as part of the app config.

**Comment by portertech** [comment]
The app is an Oauth app, not registered as Github app.

**Comment by nixwiz** [comment]
I just saw the email announcing this to the public, however the requested permissions are still the same.  Does it truly need that level of access to my repos?  I am still hesitant to share anything due to this.

**Comment by nixwiz** [comment]
Any updates on this?  It's the one thing keeping me from sharing assets at the moment.

**Comment by mbiang** [comment]
@nixwiz - I've looked into this further, and apparently Bonsai is requesting the minimum level of permissions possible via Github's OAuth Scopes.  Bonsai requires:

- Ability to read repository information, including releases, tags, and release assets.  
- Ability to create webhooks on a repository.
- Ability to read contributors on a repository.
- Ability to "star" a repository
- Ability to access basic user details, including email addresses.

Unfortunately, Github's permission system is not very granular.  In order to obtain basic repository details, as well as the ability to star a repository, we have to request the "public_repo" scope to get access to release info, contributors, as well as the ability to star a repository.   The "public_repo" scope though, contains read and write access to many other aspects of the repositories that we are not using.   See Github's docs of available scopes here:  https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps\

In total, we are requesting the following scopes:

- public_repo - necessary to read contributors, releases, release assets, and to star a repository
- user:email - allows access to user's email address(es)
- write:repo_hook - allows write acess to repository webhooks.  Bonsai adds a webhook to all registered asset repositories which notifies bonsai when a new release is created.  Bonsai then automatically registers that release as a new asset version.

**Comment by nixwiz** [comment]
Thanks for the response @mbiang .
