### ISSUE TITLE
Hosted Assets should use organization namespace

### ISSUE THREAD

**Issue by mbiang** [sensu/bonsai-asset-index#90]
** Current Behavior: **

Hosted assets currently are located under the namespace of the user that uploaded them.  For example:  https://bonsai.sensu.io/assets/portertech/sensu-jira-handler

** Desired Behavior **

- Hosted assets should appear under the main organization's namespace.   For example, the above URL should be: https://bonsai.sensu.io/assets/sensu/sensu-jira-handler
- The namespace should be configured via an ENVIRONMENT variable

**Comment by pzupan** [comment]
Changes are in pull request #93

**Comment by mbiang** [comment]
The URL appears to be producing a 404 Not Found error:   https://bonsai.sensu.io/assets/sensu/sensu-jira-handler

Also, if you click on the Sensu Jira Handler asset from the search results still doesn't load

**Comment by mbiang** [comment]
Here's a few more requirements I think will need to be implemented here:

- The asset should not be available under the uploading user's namespace:  https://bonsai.sensu.io/assets/portertech/sensu-jira-handler.  This is to prevent duplicate content issues with Search Engine optimization.   The site should show a 404 if the URL above is accessed.
- The asset should display at under the organization's namespace by default, without redirecting to another location.

**Comment by pzupan** [comment]
Treating the asset as owned by Sensu causes some issues with the owner's asset page.  Currently we are displaying the asset as owned by the individual on the individual's asset page.  Do we want to change that as well?

**Comment by mbiang** [comment]
Yes, that's a good catch - we don't want to show it there either.  For all intents and purposes, this asset should be owned by Sensu.  Do we need to rearchitect this a bit so that the user doesn't actually own the asset, but an org does?  Not exactly sure how that would look.

**Comment by pzupan** [comment]
I think the only way we can do that is to re-architect it to create a sensu owner object.  Then I suspect that object would have to be part of an organization such that other members of that organization will have admin privileges.  It seems like a lot of work, but may be necessary since the asset should survive the dis-association of an individual from the organization leaving other individuals able to administer it.  

Or perhaps we simply filter hosted assets from an individual's page and allow an administrator to transfer ownership of a hosted asset to another individual when necessary.  This would leave the site with no owner page for hosted assets (or we could patch one together for all hosted assets).

**Comment by pzupan** [comment]
Pull request #104

**Comment by pzupan** [comment]
New Pull Request #105
